"""
Module: seed_data
Layer: data (tooling, not application code)
Purpose: Static world seed data — factions, locations, characters, events, and Phase 3
         content used by the HTTP API seeder.
Does NOT: make HTTP calls or import any npc_engine application code.
Dependencies injected: None.
Used by: data.api_seeder
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


# ---------------------------------------------------------------------------
# Seed data constants
# ---------------------------------------------------------------------------

_FACTIONS = [
    {"id": "guild", "name": "Merchant Guild", "archetype": "mercantile", "description": "The powerful trade guild that controls commerce in the city.", "is_active": True},
    {"id": "guard", "name": "City Guard", "archetype": "military", "description": "The city's law enforcement and defensive force.", "is_active": True},
    {"id": "temple", "name": "Temple Order", "archetype": "religious", "description": "The religious order that runs the city's temples.", "is_active": True},
    {"id": "dockers", "name": "Dockworkers Union", "archetype": "social", "description": "The union representing dockworkers and sailors.", "is_active": True},
    {"id": "free", "name": "Free Folk", "archetype": "other", "description": "Independent citizens with no faction allegiance.", "is_active": True},
]

# (character_id, faction_id, role)
_FACTION_MEMBERS = [
    ("npc_1", "guild", "officer"),
    ("npc_6", "guild", "member"),
    ("npc_2", "guard", "officer"),
    ("npc_8", "guard", "member"),
    ("guard_1", "guard", "member"),
    ("npc_3", "temple", "officer"),
    ("npc_9", "temple", "member"),
    ("npc_4", "dockers", "officer"),
    ("npc_10", "dockers", "member"),
]

_CHARACTER_LOCATION: dict[str, tuple[str, bool]] = {
    # id -> (location_id, is_permanent_resident)
    "player_1":  ("loc_market",  False),
    "npc_1":     ("loc_market",  True),
    "npc_2":     ("loc_keep",    True),
    "npc_3":     ("loc_temple",  True),
    "npc_4":     ("loc_docks",   True),
    "npc_5":     ("loc_tavern",  True),
    "npc_6":     ("loc_market",  True),
    "npc_7":     ("loc_market",  True),
    "npc_8":     ("loc_keep",    True),
    "npc_9":     ("loc_temple",  True),
    "npc_10":    ("loc_docks",   True),
    "npc_11":    ("loc_tavern",  True),
    "guard_1":   ("loc_gate",   True),
}

_RELATES_TO_PAIRS: list[tuple[str, str]] = [
    # Same location: market
    ("npc_1", "npc_6"), ("npc_6", "npc_1"),
    ("npc_1", "npc_7"), ("npc_7", "npc_1"),
    ("npc_6", "npc_7"), ("npc_7", "npc_6"),
    # Same location: keep
    ("npc_2", "npc_8"), ("npc_8", "npc_2"),
    # Same location: temple
    ("npc_3", "npc_9"), ("npc_9", "npc_3"),
    # Same location: docks
    ("npc_4", "npc_10"), ("npc_10", "npc_4"),
    # Same location: tavern
    ("npc_5", "npc_11"), ("npc_11", "npc_5"),
    # Same faction (free), different location: tavern ↔ market
    ("npc_5", "npc_7"), ("npc_7", "npc_5"),
    ("npc_7", "npc_11"), ("npc_11", "npc_7"),
]

_EVENT_PARTICIPATION: list[dict[str, str]] = [
    {"character_id": "npc_1",  "event_id": "event_1", "role": "witness"},
    {"character_id": "npc_7",  "event_id": "event_1", "role": "witness"},
    {"character_id": "npc_2",  "event_id": "event_2", "role": "witness"},
    {"character_id": "npc_8",  "event_id": "event_2", "role": "witness"},
    {"character_id": "npc_3",  "event_id": "event_3", "role": "witness"},
    {"character_id": "npc_9",  "event_id": "event_3", "role": "witness"},
]

_NPC_IDS: list[str] = [f"npc_{i}" for i in range(1, 12)]

# ---------------------------------------------------------------------------
# Phase 3 seed data
# IDs are auto-generated by the typed admin endpoints. Re-seeding on a
# populated DB will create duplicates; wipe first if that matters.
# ---------------------------------------------------------------------------

_GAME_TIME = {"year": 1, "season": "spring", "day": 1, "time_of_day": "morning"}

# (character_id, content, confidence)
_PHASE3_BELIEFS: list[tuple[str, str, int]] = [
    ("npc_1", "The guild will betray the city if it profits them.", 80),
    ("npc_1", "Temple priests preach peace but hoard wealth.", 55),
    ("npc_2", "The guards are all in the guild's pocket.", 90),
    ("npc_2", "A stranger in town means trouble.", 40),
    ("npc_3", "The docks have always been dangerous at night.", 70),
    ("npc_4", "A deal made over ale is more binding than paper.", 65),
]

# (character_id, description, urgency)
_PHASE3_GOALS: list[tuple[str, str, int]] = [
    ("npc_1", "Expose the guild's corruption to the city council.", 75),
    ("npc_2", "Gather enough coin to leave this town.", 60),
    ("npc_3", "Find out what happened to the missing shipment.", 85),
    ("npc_4", "Win the respect of the guild officers.", 40),
]

# (owner_id, name, description, value, rarity, item_type, is_unique)
_PHASE3_ITEMS: list[tuple[str, str, str, int, str, str, bool]] = [
    ("npc_1", "Guild Ledger", "Detailed record of guild transactions.", 500, "rare", "document", True),
    ("npc_3", "Smuggler's Compass", "Points toward nearby contraband.", 150, "uncommon", "tool", False),
    ("npc_4", "Silver Dagger", "A foreman's sidearm.", 80, "common", "weapon", False),
]

# (character_id, content, severity)
_PHASE3_SECRETS: list[tuple[str, str, int]] = [
    ("npc_1", "The guild master paid off the city treasurer last winter.", 80),
    ("npc_2", "There is a secret tunnel from the tavern to the docks.", 60),
]

# (character_id, content, vividness, emotional_charge)
_PHASE3_MEMORIES: list[tuple[str, str, int, int]] = [
    ("npc_1", "The night the guild burned the merchant's warehouse. I watched from across the street.", 85, 70),
    ("npc_2", "The day I arrived in this town with nothing but a satchel and a lie.", 90, -60),
]

# (debtor_id, creditor_id, kind, magnitude, due_by)
_PHASE3_DEBTS: list[tuple[str, str, str, str, str]] = [
    ("npc_1", "npc_2", "favor", "Promised to speak on Sera's behalf to the guild.", "Year 1 Spring Day 10"),
    ("npc_3", "npc_4", "money", "50 gold for dock fees paid in advance.", "Year 1 Spring Day 15"),
]


def get_factions() -> list[dict[str, Any]]:
    """Return the static faction seed list."""
    return list(_FACTIONS)


def get_faction_members() -> list[tuple[str, str, str]]:
    """Return (character_id, faction_id, role) tuples."""
    return list(_FACTION_MEMBERS)


def get_character_location() -> dict[str, tuple[str, bool]]:
    """Return {character_id: (location_id, is_permanent_resident)} mapping."""
    return dict(_CHARACTER_LOCATION)


def get_relates_to_pairs() -> list[tuple[str, str]]:
    """Return (src, dst) character pairs for RELATES_TO edges."""
    return list(_RELATES_TO_PAIRS)


def get_event_participation() -> list[dict[str, str]]:
    """Return PARTICIPATED_IN seeding records."""
    return list(_EVENT_PARTICIPATION)


def get_npc_ids() -> list[str]:
    """Return stable NPC id list (npc_1..npc_11)."""
    return list(_NPC_IDS)


def get_game_time() -> dict[str, Any]:
    """Return default game time dict for Phase 3 typed endpoints."""
    return dict(_GAME_TIME)


def get_phase3_beliefs() -> list[tuple[str, str, int]]:
    """Return (character_id, content, confidence) belief tuples."""
    return list(_PHASE3_BELIEFS)


def get_phase3_goals() -> list[tuple[str, str, int]]:
    """Return (character_id, description, urgency) goal tuples."""
    return list(_PHASE3_GOALS)


def get_phase3_items() -> list[tuple[str, str, str, int, str, str, bool]]:
    """Return (owner_id, name, description, value, rarity, item_type, is_unique) item tuples."""
    return list(_PHASE3_ITEMS)


def get_phase3_secrets() -> list[tuple[str, str, int]]:
    """Return (character_id, content, severity) secret tuples."""
    return list(_PHASE3_SECRETS)


def get_phase3_memories() -> list[tuple[str, str, int, int]]:
    """Return (character_id, content, vividness, emotional_charge) memory tuples."""
    return list(_PHASE3_MEMORIES)


def get_phase3_debts() -> list[tuple[str, str, str, str, str]]:
    """Return (debtor_id, creditor_id, kind, magnitude, due_by) debt tuples."""
    return list(_PHASE3_DEBTS)


def get_locations(now: str) -> list[dict[str, Any]]:
    """Return location property dicts with a consistent timestamp."""
    return [
        {"id": "loc_tavern", "name": "Iron Lantern", "region": "North", "location_tag": "tavern", "descriptor": "A busy tavern.", "last_graph_updated_at": now},
        {"id": "loc_market", "name": "Grand Market", "region": "Central", "location_tag": "market", "descriptor": "Crowded stalls.", "last_graph_updated_at": now},
        {"id": "loc_keep", "name": "Stone Keep", "region": "Central", "location_tag": "keep", "descriptor": "Fortified keep.", "last_graph_updated_at": now},
        {"id": "loc_docks", "name": "Salt Docks", "region": "South", "location_tag": "docks", "descriptor": "Trading harbor.", "last_graph_updated_at": now},
        {"id": "loc_temple", "name": "Sun Temple", "region": "East", "location_tag": "temple", "descriptor": "Quiet sanctuary.", "last_graph_updated_at": now},
        {"id": "loc_gate", "name": "City Gate", "region": "North", "location_tag": "gate", "descriptor": "The northern gate checkpoint.", "last_graph_updated_at": now},
    ]


def get_characters(now: str) -> list[dict[str, Any]]:
    """Return character property dicts with a consistent timestamp."""
    return [
        {"id": "player_1", "name": "Player", "archetype": "adventurer", "faction": "free", "biography": "A wandering player.", "is_player": True, "is_active": False, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 50, "credulity": 50, "honesty": 50, "current_mood": "neutral"},
        {"id": "npc_1", "name": "Aldric", "archetype": "merchant", "faction": "guild", "biography": "Veteran merchant.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 70, "credulity": 45, "honesty": 65, "current_mood": "neutral"},
        {"id": "npc_2", "name": "Sera", "archetype": "guard", "faction": "guard", "biography": "City guard captain.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 30, "credulity": 35, "honesty": 80, "current_mood": "neutral"},
        {"id": "npc_3", "name": "Mira", "archetype": "healer", "faction": "temple", "biography": "Temple healer.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 45, "credulity": 65, "honesty": 75, "current_mood": "neutral"},
        {"id": "npc_4", "name": "Garr", "archetype": "sailor", "faction": "dockers", "biography": "Dock foreman.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 80, "credulity": 55, "honesty": 40, "current_mood": "neutral"},
        {"id": "npc_5", "name": "Lenna", "archetype": "barkeep", "faction": "free", "biography": "Runs the tavern.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 85, "credulity": 50, "honesty": 55, "current_mood": "neutral"},
        {"id": "npc_6", "name": "Ivor", "archetype": "scribe", "faction": "guild", "biography": "Guild record keeper.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 35, "credulity": 40, "honesty": 70, "current_mood": "neutral"},
        {"id": "npc_7", "name": "Rook", "archetype": "thief", "faction": "free", "biography": "Streetwise pickpocket.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 90, "credulity": 45, "honesty": 25, "current_mood": "neutral"},
        {"id": "npc_8", "name": "Bran", "archetype": "guard", "faction": "guard", "biography": "Gate sentry.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 25, "credulity": 40, "honesty": 75, "current_mood": "neutral"},
        {"id": "npc_9", "name": "Thalia", "archetype": "acolyte", "faction": "temple", "biography": "Young acolyte.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 50, "credulity": 75, "honesty": 60, "current_mood": "neutral"},
        {"id": "npc_10", "name": "Dorn", "archetype": "fisher", "faction": "dockers", "biography": "Harbor fisher.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 60, "credulity": 60, "honesty": 50, "current_mood": "neutral"},
        {"id": "npc_11", "name": "Edda", "archetype": "bard", "faction": "free", "biography": "Traveling bard.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 88, "credulity": 42, "honesty": 52, "current_mood": "neutral"},
        {"id": "guard_1", "name": "Halvard", "archetype": "guard", "faction": "guard", "biography": "Veteran gate guard who has watched the north road for fifteen years.", "is_player": False, "is_active": True, "created_at": now, "updated_at": now, "last_graph_updated_at": now, "gossipy": 20, "credulity": 35, "honesty": 85, "current_mood": "neutral"},
    ]


def get_events(now: str) -> list[dict[str, Any]]:
    """Return event property dicts with a current timestamp."""
    return [
        {"id": "event_1", "summary": "A fire damaged the south warehouse.", "severity": 70, "location_id": "loc_market", "occurred_at": now, "tick_id": 1, "event_type": "crime", "is_public": True, "last_graph_updated_at": now},
        {"id": "event_2", "summary": "Bandits clashed with guards at the north gate.", "severity": 60, "location_id": "loc_keep", "occurred_at": now, "tick_id": 2, "event_type": "battle", "is_public": True, "last_graph_updated_at": now},
        {"id": "event_3", "summary": "A rare relic was discovered near the temple.", "severity": 50, "location_id": "loc_temple", "occurred_at": now, "tick_id": 3, "event_type": "discovery", "is_public": True, "last_graph_updated_at": now},
    ]


def now_iso() -> str:
    """Return current UTC timestamp as ISO 8601 string."""
    return datetime.now(timezone.utc).isoformat()
